# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '_account_settings.ui'
#
# Created: Tue Oct  5 20:12:45 2010
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(326, 392)
        self.verticalLayout = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtGui.QLabel(Dialog)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.label_2 = QtGui.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtGui.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_3)
        self.username = QtGui.QLineEdit(Dialog)
        self.username.setObjectName("username")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.username)
        self.password = QtGui.QLineEdit(Dialog)
        self.password.setEchoMode(QtGui.QLineEdit.Password)
        self.password.setObjectName("password")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.password)
        self.improto = QtGui.QComboBox(Dialog)
        self.improto.setObjectName("improto")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.improto)
        self.verticalLayout.addLayout(self.formLayout)
        self.autoconnect = QtGui.QCheckBox(Dialog)
        self.autoconnect.setObjectName("autoconnect")
        self.verticalLayout.addWidget(self.autoconnect)
        self.use_proxy = QtGui.QCheckBox(Dialog)
        self.use_proxy.setObjectName("use_proxy")
        self.verticalLayout.addWidget(self.use_proxy)
        self.proxy_params = QtGui.QFrame(Dialog)
        self.proxy_params.setEnabled(False)
        self.proxy_params.setFrameShape(QtGui.QFrame.StyledPanel)
        self.proxy_params.setFrameShadow(QtGui.QFrame.Raised)
        self.proxy_params.setObjectName("proxy_params")
        self.formLayout_2 = QtGui.QFormLayout(self.proxy_params)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_4 = QtGui.QLabel(self.proxy_params)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtGui.QLabel(self.proxy_params)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_5)
        self.label_6 = QtGui.QLabel(self.proxy_params)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_6)
        self.label_7 = QtGui.QLabel(self.proxy_params)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_7)
        self.label_8 = QtGui.QLabel(self.proxy_params)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_8)
        self.proxy_type = QtGui.QComboBox(self.proxy_params)
        self.proxy_type.setObjectName("proxy_type")
        self.proxy_type.addItem("")
        self.proxy_type.addItem("")
        self.proxy_type.addItem("")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.proxy_type)
        self.proxy_address = QtGui.QLineEdit(self.proxy_params)
        self.proxy_address.setObjectName("proxy_address")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.proxy_address)
        self.proxy_port = QtGui.QLineEdit(self.proxy_params)
        self.proxy_port.setObjectName("proxy_port")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.proxy_port)
        self.proxy_username = QtGui.QLineEdit(self.proxy_params)
        self.proxy_username.setObjectName("proxy_username")
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.proxy_username)
        self.proxy_password = QtGui.QLineEdit(self.proxy_params)
        self.proxy_password.setEchoMode(QtGui.QLineEdit.Password)
        self.proxy_password.setObjectName("proxy_password")
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.FieldRole, self.proxy_password)
        self.verticalLayout.addWidget(self.proxy_params)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), Dialog.reject)
        QtCore.QObject.connect(self.use_proxy, QtCore.SIGNAL("toggled(bool)"), self.proxy_params.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Username", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Password", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "Protocol", None, QtGui.QApplication.UnicodeUTF8))
        self.autoconnect.setText(QtGui.QApplication.translate("Dialog", "Auto connect", None, QtGui.QApplication.UnicodeUTF8))
        self.use_proxy.setText(QtGui.QApplication.translate("Dialog", "Proxy..", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "Type", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "Server", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog", "Port", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dialog", "Username", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Dialog", "Password", None, QtGui.QApplication.UnicodeUTF8))
        self.proxy_type.setItemText(0, QtGui.QApplication.translate("Dialog", "HTTP", None, QtGui.QApplication.UnicodeUTF8))
        self.proxy_type.setItemText(1, QtGui.QApplication.translate("Dialog", "SOCKS4", None, QtGui.QApplication.UnicodeUTF8))
        self.proxy_type.setItemText(2, QtGui.QApplication.translate("Dialog", "SOCKS5", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Dialog = QtGui.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

