# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chatwindow_auto.ui'
#
# Created: Mon Oct 18 16:14:06 2010
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_w_chatwindow(object):
    def setupUi(self, w_chatwindow):
        w_chatwindow.setObjectName("w_chatwindow")
        w_chatwindow.resize(466, 529)
        self.centralwidget = QtGui.QWidget(w_chatwindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.splitter_2 = QtGui.QSplitter(self.centralwidget)
        self.splitter_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.splitter_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.splitter_2.setLineWidth(1)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setHandleWidth(6)
        self.splitter_2.setChildrenCollapsible(False)
        self.splitter_2.setObjectName("splitter_2")
        self.w_chatframe = QtGui.QFrame(self.splitter_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.w_chatframe.sizePolicy().hasHeightForWidth())
        self.w_chatframe.setSizePolicy(sizePolicy)
        self.w_chatframe.setFrameShadow(QtGui.QFrame.Raised)
        self.w_chatframe.setLineWidth(0)
        self.w_chatframe.setObjectName("w_chatframe")
        self.gridLayout = QtGui.QGridLayout(self.w_chatframe)
        self.gridLayout.setMargin(0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter_3 = QtGui.QSplitter(self.w_chatframe)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.convtext = QtGui.QTextBrowser(self.splitter_3)
        self.convtext.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.convtext.sizePolicy().hasHeightForWidth())
        self.convtext.setSizePolicy(sizePolicy)
        self.convtext.setAcceptDrops(False)
        self.convtext.setStyleSheet("QTextEdit {\n"
"background:palette(base);\n"
"border-radius:4px;\n"
"border:2px inset palette(dark);\n"
"border-bottom-style: groove;\n"
"border-right-style:groove;\n"
"}")
        self.convtext.setFrameShape(QtGui.QFrame.WinPanel)
        self.convtext.setFrameShadow(QtGui.QFrame.Sunken)
        self.convtext.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.convtext.setHtml("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Lucida Grande\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p></body></html>")
        self.convtext.setOpenLinks(False)
        self.convtext.setObjectName("convtext")
        self.userlists = QtGui.QSplitter(self.splitter_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.userlists.sizePolicy().hasHeightForWidth())
        self.userlists.setSizePolicy(sizePolicy)
        self.userlists.setMinimumSize(QtCore.QSize(80, 0))
        self.userlists.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.userlists.setStyleSheet("None")
        self.userlists.setFrameShape(QtGui.QFrame.WinPanel)
        self.userlists.setFrameShadow(QtGui.QFrame.Sunken)
        self.userlists.setOrientation(QtCore.Qt.Vertical)
        self.userlists.setObjectName("userlists")
        self.userlist = QtGui.QListWidget(self.userlists)
        self.userlist.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.userlist.sizePolicy().hasHeightForWidth())
        self.userlist.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(50)
        font.setItalic(False)
        font.setStrikeOut(False)
        font.setBold(False)
        self.userlist.setFont(font)
        self.userlist.setStyleSheet("::item {font-weight:bold; margin:0px;}\n"
"\n"
"::item:selected { background-color:palette(highlight);\n"
"border: 1px solid black;\n"
"border-radius:3px;\n"
"font-weight:bold;\n"
"margin:2px;\n"
"}")
        self.userlist.setFrameShape(QtGui.QFrame.NoFrame)
        self.userlist.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.userlist.setAlternatingRowColors(True)
        self.userlist.setSpacing(-1)
        self.userlist.setObjectName("userlist")
        QtGui.QListWidgetItem(self.userlist)
        QtGui.QListWidgetItem(self.userlist)
        QtGui.QListWidgetItem(self.userlist)
        QtGui.QListWidgetItem(self.userlist)
        QtGui.QListWidgetItem(self.userlist)
        QtGui.QListWidgetItem(self.userlist)
        QtGui.QListWidgetItem(self.userlist)
        QtGui.QListWidgetItem(self.userlist)
        QtGui.QListWidgetItem(self.userlist)
        QtGui.QListWidgetItem(self.userlist)
        QtGui.QListWidgetItem(self.userlist)
        QtGui.QListWidgetItem(self.userlist)
        QtGui.QListWidgetItem(self.userlist)
        QtGui.QListWidgetItem(self.userlist)
        QtGui.QListWidgetItem(self.userlist)
        self.ignorelist = QtGui.QListWidget(self.userlists)
        self.ignorelist.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ignorelist.sizePolicy().hasHeightForWidth())
        self.ignorelist.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(50)
        font.setItalic(False)
        font.setStrikeOut(False)
        font.setBold(False)
        self.ignorelist.setFont(font)
        self.ignorelist.setStyleSheet("QAbstractItemView {background-color:palette(window);}\n"
"\n"
"::item:selected {\n"
"background-color: palette(base);\n"
"border: 1px solid palette(dark);\n"
"border-radius:5px;\n"
"margin:2px;\n"
"}")
        self.ignorelist.setFrameShape(QtGui.QFrame.NoFrame)
        self.ignorelist.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.ignorelist.setAlternatingRowColors(False)
        self.ignorelist.setSpacing(-2)
        self.ignorelist.setViewMode(QtGui.QListView.ListMode)
        self.ignorelist.setWordWrap(False)
        self.ignorelist.setObjectName("ignorelist")
        QtGui.QListWidgetItem(self.ignorelist)
        QtGui.QListWidgetItem(self.ignorelist)
        QtGui.QListWidgetItem(self.ignorelist)
        QtGui.QListWidgetItem(self.ignorelist)
        QtGui.QListWidgetItem(self.ignorelist)
        QtGui.QListWidgetItem(self.ignorelist)
        QtGui.QListWidgetItem(self.ignorelist)
        QtGui.QListWidgetItem(self.ignorelist)
        QtGui.QListWidgetItem(self.ignorelist)
        QtGui.QListWidgetItem(self.ignorelist)
        QtGui.QListWidgetItem(self.ignorelist)
        QtGui.QListWidgetItem(self.ignorelist)
        QtGui.QListWidgetItem(self.ignorelist)
        QtGui.QListWidgetItem(self.ignorelist)
        QtGui.QListWidgetItem(self.ignorelist)
        self.gridLayout.addWidget(self.splitter_3, 0, 0, 1, 1)
        self.w_inputframe_2 = QtGui.QFrame(self.splitter_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.w_inputframe_2.sizePolicy().hasHeightForWidth())
        self.w_inputframe_2.setSizePolicy(sizePolicy)
        self.w_inputframe_2.setStyleSheet("QFrame#w_inputframe_2 {\n"
"border: 2px inset palette(dark);\n"
"border-radius:6px;\n"
"border-bottom: 1px groove palette(dark);\n"
"border-right:1px groove palette(dark);\n"
"}\n"
"QFrame#w_inputframe_2, QTextEdit {\n"
"border-bottom-right-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"}\n"
"#input {\n"
"background: palette(base);\n"
"border-top: 1px groove palette(dark);\n"
"}")
        self.w_inputframe_2.setFrameShape(QtGui.QFrame.WinPanel)
        self.w_inputframe_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.w_inputframe_2.setLineWidth(1)
        self.w_inputframe_2.setMidLineWidth(0)
        self.w_inputframe_2.setObjectName("w_inputframe_2")
        self.w_inputframe = QtGui.QVBoxLayout(self.w_inputframe_2)
        self.w_inputframe.setSpacing(3)
        self.w_inputframe.setMargin(0)
        self.w_inputframe.setObjectName("w_inputframe")
        self.w_formatframe = QtGui.QFrame(self.w_inputframe_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w_formatframe.sizePolicy().hasHeightForWidth())
        self.w_formatframe.setSizePolicy(sizePolicy)
        self.w_formatframe.setFrameShape(QtGui.QFrame.NoFrame)
        self.w_formatframe.setFrameShadow(QtGui.QFrame.Sunken)
        self.w_formatframe.setObjectName("w_formatframe")
        self.gridLayout_3 = QtGui.QGridLayout(self.w_formatframe)
        self.gridLayout_3.setContentsMargins(5, 1, 5, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.font = QtGui.QFontComboBox(self.w_formatframe)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.font.sizePolicy().hasHeightForWidth())
        self.font.setSizePolicy(sizePolicy)
        self.font.setMinimumSize(QtCore.QSize(0, 0))
        self.font.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.font.setFont(font)
        self.font.setFrame(False)
        self.font.setObjectName("font")
        self.gridLayout_3.addWidget(self.font, 0, 8, 1, 1)
        spacerItem = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 0, 10, 1, 1)
        self.fontsize = QtGui.QSpinBox(self.w_formatframe)
        self.fontsize.setMinimum(6)
        self.fontsize.setMaximum(48)
        self.fontsize.setProperty("value", 10)
        self.fontsize.setObjectName("fontsize")
        self.gridLayout_3.addWidget(self.fontsize, 0, 9, 1, 1)
        self.format_button_frame = QtGui.QFrame(self.w_formatframe)
        self.format_button_frame.setStyleSheet(":open { background-color:palette(dark); \n"
"border-top: 2px inset rgba(0,0,0,130);\n"
"border-left: 2px inset rgba(0,0,0,130);\n"
"border-radius:3px;\n"
"\n"
"margin-right:1px;\n"
"margin-top:2px;\n"
"margin-bottom:2px\n"
"}")
        self.format_button_frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.format_button_frame.setFrameShadow(QtGui.QFrame.Plain)
        self.format_button_frame.setLineWidth(1)
        self.format_button_frame.setMidLineWidth(0)
        self.format_button_frame.setObjectName("format_button_frame")
        self.horizontalLayout = QtGui.QHBoxLayout(self.format_button_frame)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.bold = QtGui.QPushButton(self.format_button_frame)
        self.bold.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bold.sizePolicy().hasHeightForWidth())
        self.bold.setSizePolicy(sizePolicy)
        self.bold.setMaximumSize(QtCore.QSize(24, 27))
        self.bold.setFocusPolicy(QtCore.Qt.NoFocus)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/format-text-bold.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bold.setIcon(icon)
        self.bold.setCheckable(True)
        self.bold.setChecked(False)
        self.bold.setFlat(True)
        self.bold.setObjectName("bold")
        self.horizontalLayout.addWidget(self.bold)
        self.italic = QtGui.QPushButton(self.format_button_frame)
        self.italic.setEnabled(True)
        self.italic.setMaximumSize(QtCore.QSize(24, 27))
        self.italic.setFocusPolicy(QtCore.Qt.NoFocus)
        self.italic.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/format-text-italic.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.italic.setIcon(icon1)
        self.italic.setIconSize(QtCore.QSize(24, 24))
        self.italic.setCheckable(True)
        self.italic.setChecked(False)
        self.italic.setFlat(True)
        self.italic.setObjectName("italic")
        self.horizontalLayout.addWidget(self.italic)
        self.underline = QtGui.QPushButton(self.format_button_frame)
        self.underline.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.underline.sizePolicy().hasHeightForWidth())
        self.underline.setSizePolicy(sizePolicy)
        self.underline.setMaximumSize(QtCore.QSize(24, 27))
        self.underline.setFocusPolicy(QtCore.Qt.NoFocus)
        self.underline.setStyleSheet("None")
        self.underline.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/format-text-underline.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.underline.setIcon(icon2)
        self.underline.setIconSize(QtCore.QSize(24, 24))
        self.underline.setCheckable(True)
        self.underline.setChecked(False)
        self.underline.setFlat(True)
        self.underline.setObjectName("underline")
        self.horizontalLayout.addWidget(self.underline)
        self.gridLayout_3.addWidget(self.format_button_frame, 0, 5, 1, 1)
        self.fg_color = QtGui.QToolButton(self.w_formatframe)
        self.fg_color.setMinimumSize(QtCore.QSize(27, 24))
        self.fg_color.setMaximumSize(QtCore.QSize(24, 27))
        self.fg_color.setStyleSheet("None")
        self.fg_color.setText("")
        self.fg_color.setIconSize(QtCore.QSize(24, 24))
        self.fg_color.setAutoRaise(True)
        self.fg_color.setObjectName("fg_color")
        self.gridLayout_3.addWidget(self.fg_color, 0, 7, 1, 1)
        self.frame = QtGui.QFrame(self.w_formatframe)
        self.frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setLineWidth(0)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.zoom_in = QtGui.QToolButton(self.frame)
        self.zoom_in.setMaximumSize(QtCore.QSize(24, 24))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/res/16x16/actions/zoom-in.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.zoom_in.setIcon(icon3)
        self.zoom_in.setAutoRaise(True)
        self.zoom_in.setObjectName("zoom_in")
        self.horizontalLayout_2.addWidget(self.zoom_in)
        self.zoom_orig = QtGui.QToolButton(self.frame)
        self.zoom_orig.setMaximumSize(QtCore.QSize(24, 24))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/res/16x16/actions/zoom-original.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.zoom_orig.setIcon(icon4)
        self.zoom_orig.setAutoRaise(True)
        self.zoom_orig.setObjectName("zoom_orig")
        self.horizontalLayout_2.addWidget(self.zoom_orig)
        self.zoom_out = QtGui.QToolButton(self.frame)
        self.zoom_out.setMaximumSize(QtCore.QSize(24, 24))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/res/16x16/actions/zoom-out.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.zoom_out.setIcon(icon5)
        self.zoom_out.setAutoRaise(True)
        self.zoom_out.setObjectName("zoom_out")
        self.horizontalLayout_2.addWidget(self.zoom_out)
        self.gridLayout_3.addWidget(self.frame, 0, 11, 1, 1)
        self.w_inputframe.addWidget(self.w_formatframe)
        self.input = QtGui.QTextEdit(self.w_inputframe_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.input.sizePolicy().hasHeightForWidth())
        self.input.setSizePolicy(sizePolicy)
        self.input.setMinimumSize(QtCore.QSize(0, 50))
        self.input.setMaximumSize(QtCore.QSize(16777215, 1000))
        self.input.setSizeIncrement(QtCore.QSize(1, 1))
        self.input.setStyleSheet("None")
        self.input.setFrameShape(QtGui.QFrame.NoFrame)
        self.input.setLineWidth(10)
        self.input.setMidLineWidth(10)
        self.input.setAcceptRichText(True)
        self.input.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextEditable|QtCore.Qt.TextEditorInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.input.setObjectName("input")
        self.w_inputframe.addWidget(self.input)
        self.gridLayout_2.addWidget(self.splitter_2, 2, 0, 1, 1)
        self.chat_topic = QtGui.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setBold(True)
        self.chat_topic.setFont(font)
        self.chat_topic.setAutoFillBackground(False)
        self.chat_topic.setStyleSheet("QLineEdit {background-color:rgba(0,0,0,25);\n"
"border: 2px inset palette(dark);\n"
"border-radius:6px;\n"
"margin:0px;\n"
"padding:0px;\n"
"}")
        self.chat_topic.setAlignment(QtCore.Qt.AlignCenter)
        self.chat_topic.setReadOnly(True)
        self.chat_topic.setObjectName("chat_topic")
        self.gridLayout_2.addWidget(self.chat_topic, 1, 0, 1, 1)
        w_chatwindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(w_chatwindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 466, 29))
        self.menubar.setObjectName("menubar")
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuActions = QtGui.QMenu(self.menubar)
        self.menuActions.setObjectName("menuActions")
        w_chatwindow.setMenuBar(self.menubar)
        self.actionShow_Formatting_Toolbox = QtGui.QAction(w_chatwindow)
        self.actionShow_Formatting_Toolbox.setCheckable(True)
        self.actionShow_Formatting_Toolbox.setChecked(True)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/icons/format-text-subscript.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionShow_Formatting_Toolbox.setIcon(icon6)
        self.actionShow_Formatting_Toolbox.setObjectName("actionShow_Formatting_Toolbox")
        self.actionShow_User_List = QtGui.QAction(w_chatwindow)
        self.actionShow_User_List.setCheckable(True)
        self.actionShow_User_List.setChecked(True)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/icons/format-list-unordered.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionShow_User_List.setIcon(icon7)
        self.actionShow_User_List.setObjectName("actionShow_User_List")
        self.actionShow_Backlog = QtGui.QAction(w_chatwindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/icons/text-x-log.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionShow_Backlog.setIcon(icon8)
        self.actionShow_Backlog.setObjectName("actionShow_Backlog")
        self.actionClose = QtGui.QAction(w_chatwindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/icons/application-exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionClose.setIcon(icon9)
        self.actionClose.setObjectName("actionClose")
        self.actionLeave = QtGui.QAction(w_chatwindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icons/icons/log-out.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLeave.setIcon(icon10)
        self.actionLeave.setObjectName("actionLeave")
        self.actionTimestamps = QtGui.QAction(w_chatwindow)
        self.actionTimestamps.setCheckable(True)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/icons/icons/clock.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionTimestamps.setIcon(icon11)
        self.actionTimestamps.setObjectName("actionTimestamps")
        self.actionShow_Ignore_List = QtGui.QAction(w_chatwindow)
        self.actionShow_Ignore_List.setCheckable(True)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/icons/res/16x16/actions/dialog-cancel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionShow_Ignore_List.setIcon(icon12)
        self.actionShow_Ignore_List.setObjectName("actionShow_Ignore_List")
        self.actionShow_Join_Leave = QtGui.QAction(w_chatwindow)
        self.actionShow_Join_Leave.setCheckable(True)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/icons/icons/info.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionShow_Join_Leave.setIcon(icon13)
        self.actionShow_Join_Leave.setObjectName("actionShow_Join_Leave")
        self.actionShow_Topic = QtGui.QAction(w_chatwindow)
        self.actionShow_Topic.setCheckable(True)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/icons/icons/format-line-spacing-normal.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionShow_Topic.setIcon(icon14)
        self.actionShow_Topic.setObjectName("actionShow_Topic")
        self.menuView.addAction(self.actionShow_Formatting_Toolbox)
        self.menuView.addAction(self.actionTimestamps)
        self.menuActions.addAction(self.actionShow_Backlog)
        self.menuActions.addAction(self.actionClose)
        self.menubar.addAction(self.menuActions.menuAction())
        self.menubar.addAction(self.menuView.menuAction())

        self.retranslateUi(w_chatwindow)
        QtCore.QObject.connect(self.font, QtCore.SIGNAL("currentFontChanged(QFont)"), self.input.setCurrentFont)
        QtCore.QObject.connect(self.actionShow_Formatting_Toolbox, QtCore.SIGNAL("toggled(bool)"), self.w_formatframe.setVisible)
        QtCore.QObject.connect(self.actionShow_User_List, QtCore.SIGNAL("toggled(bool)"), self.userlists.setVisible)
        QtCore.QObject.connect(self.actionClose, QtCore.SIGNAL("activated()"), w_chatwindow.close)
        QtCore.QObject.connect(self.userlist, QtCore.SIGNAL("itemDoubleClicked(QListWidgetItem*)"), self.input.selectAll)
        QtCore.QObject.connect(self.actionShow_Ignore_List, QtCore.SIGNAL("toggled(bool)"), self.ignorelist.setVisible)
        QtCore.QObject.connect(self.italic, QtCore.SIGNAL("toggled(bool)"), self.input.setFontItalic)
        QtCore.QObject.connect(self.underline, QtCore.SIGNAL("toggled(bool)"), self.input.setFontUnderline)
        QtCore.QObject.connect(self.actionShow_Topic, QtCore.SIGNAL("toggled(bool)"), self.chat_topic.setVisible)
        QtCore.QMetaObject.connectSlotsByName(w_chatwindow)

    def retranslateUi(self, w_chatwindow):
        w_chatwindow.setWindowTitle(QtGui.QApplication.translate("w_chatwindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.userlist.setSortingEnabled(True)
        __sortingEnabled = self.userlist.isSortingEnabled()
        self.userlist.setSortingEnabled(False)
        self.userlist.item(0).setText(QtGui.QApplication.translate("w_chatwindow", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.userlist.item(1).setText(QtGui.QApplication.translate("w_chatwindow", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.userlist.item(2).setText(QtGui.QApplication.translate("w_chatwindow", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.userlist.item(3).setText(QtGui.QApplication.translate("w_chatwindow", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.userlist.item(4).setText(QtGui.QApplication.translate("w_chatwindow", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.userlist.item(5).setText(QtGui.QApplication.translate("w_chatwindow", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.userlist.item(6).setText(QtGui.QApplication.translate("w_chatwindow", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.userlist.item(7).setText(QtGui.QApplication.translate("w_chatwindow", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.userlist.item(8).setText(QtGui.QApplication.translate("w_chatwindow", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.userlist.item(9).setText(QtGui.QApplication.translate("w_chatwindow", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.userlist.item(10).setText(QtGui.QApplication.translate("w_chatwindow", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.userlist.item(11).setText(QtGui.QApplication.translate("w_chatwindow", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.userlist.item(12).setText(QtGui.QApplication.translate("w_chatwindow", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.userlist.item(13).setText(QtGui.QApplication.translate("w_chatwindow", "asdfasdfa", None, QtGui.QApplication.UnicodeUTF8))
        self.userlist.item(14).setText(QtGui.QApplication.translate("w_chatwindow", "sssssssssssssssssssssssssssssssssssssssssssssssssssssssss", None, QtGui.QApplication.UnicodeUTF8))
        self.userlist.setSortingEnabled(__sortingEnabled)
        self.ignorelist.setSortingEnabled(True)
        __sortingEnabled = self.ignorelist.isSortingEnabled()
        self.ignorelist.setSortingEnabled(False)
        self.ignorelist.item(0).setText(QtGui.QApplication.translate("w_chatwindow", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.ignorelist.item(1).setText(QtGui.QApplication.translate("w_chatwindow", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.ignorelist.item(2).setText(QtGui.QApplication.translate("w_chatwindow", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.ignorelist.item(3).setText(QtGui.QApplication.translate("w_chatwindow", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.ignorelist.item(4).setText(QtGui.QApplication.translate("w_chatwindow", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.ignorelist.item(5).setText(QtGui.QApplication.translate("w_chatwindow", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.ignorelist.item(6).setText(QtGui.QApplication.translate("w_chatwindow", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.ignorelist.item(7).setText(QtGui.QApplication.translate("w_chatwindow", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.ignorelist.item(8).setText(QtGui.QApplication.translate("w_chatwindow", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.ignorelist.item(9).setText(QtGui.QApplication.translate("w_chatwindow", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.ignorelist.item(10).setText(QtGui.QApplication.translate("w_chatwindow", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.ignorelist.item(11).setText(QtGui.QApplication.translate("w_chatwindow", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.ignorelist.item(12).setText(QtGui.QApplication.translate("w_chatwindow", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.ignorelist.item(13).setText(QtGui.QApplication.translate("w_chatwindow", "asdfasdfa", None, QtGui.QApplication.UnicodeUTF8))
        self.ignorelist.item(14).setText(QtGui.QApplication.translate("w_chatwindow", "sssssssssssssssssssssssssssssssssssssssssssssssssssssssss", None, QtGui.QApplication.UnicodeUTF8))
        self.ignorelist.setSortingEnabled(__sortingEnabled)
        self.fontsize.setSuffix(QtGui.QApplication.translate("w_chatwindow", "pt", None, QtGui.QApplication.UnicodeUTF8))
        self.bold.setShortcut(QtGui.QApplication.translate("w_chatwindow", "Ctrl+B", None, QtGui.QApplication.UnicodeUTF8))
        self.italic.setShortcut(QtGui.QApplication.translate("w_chatwindow", "Ctrl+I", None, QtGui.QApplication.UnicodeUTF8))
        self.underline.setShortcut(QtGui.QApplication.translate("w_chatwindow", "Ctrl+U", None, QtGui.QApplication.UnicodeUTF8))
        self.fg_color.setToolTip(QtGui.QApplication.translate("w_chatwindow", "Change Color", None, QtGui.QApplication.UnicodeUTF8))
        self.zoom_in.setToolTip(QtGui.QApplication.translate("w_chatwindow", "Zoom In", None, QtGui.QApplication.UnicodeUTF8))
        self.zoom_in.setText(QtGui.QApplication.translate("w_chatwindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.zoom_orig.setToolTip(QtGui.QApplication.translate("w_chatwindow", "Original Size", None, QtGui.QApplication.UnicodeUTF8))
        self.zoom_orig.setText(QtGui.QApplication.translate("w_chatwindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.zoom_out.setToolTip(QtGui.QApplication.translate("w_chatwindow", "Zoom Out", None, QtGui.QApplication.UnicodeUTF8))
        self.zoom_out.setText(QtGui.QApplication.translate("w_chatwindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.input.setHtml(QtGui.QApplication.translate("w_chatwindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Lucida Grande\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.chat_topic.setText(QtGui.QApplication.translate("w_chatwindow", "ALL YOUR BASE ARE BELONG TO US", None, QtGui.QApplication.UnicodeUTF8))
        self.menuView.setTitle(QtGui.QApplication.translate("w_chatwindow", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.menuActions.setTitle(QtGui.QApplication.translate("w_chatwindow", "Actions", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShow_Formatting_Toolbox.setText(QtGui.QApplication.translate("w_chatwindow", "Formatting Toolbox", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShow_Formatting_Toolbox.setShortcut(QtGui.QApplication.translate("w_chatwindow", "Ctrl+Shift+F", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShow_User_List.setText(QtGui.QApplication.translate("w_chatwindow", "User List", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShow_Backlog.setText(QtGui.QApplication.translate("w_chatwindow", "Show Backlog", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClose.setText(QtGui.QApplication.translate("w_chatwindow", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClose.setShortcut(QtGui.QApplication.translate("w_chatwindow", "Ctrl+W", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLeave.setText(QtGui.QApplication.translate("w_chatwindow", "Leave", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTimestamps.setText(QtGui.QApplication.translate("w_chatwindow", "Timestamps", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShow_Ignore_List.setText(QtGui.QApplication.translate("w_chatwindow", "Ignore List", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShow_Join_Leave.setText(QtGui.QApplication.translate("w_chatwindow", "Show Join/Leave", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShow_Topic.setText(QtGui.QApplication.translate("w_chatwindow", "Show Topic", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    w_chatwindow = QtGui.QMainWindow()
    ui = Ui_w_chatwindow()
    ui.setupUi(w_chatwindow)
    w_chatwindow.show()
    sys.exit(app.exec_())

