# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chatwindow.ui'
#
# Created: Tue Aug 10 10:50:17 2010
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
import lxml.html as html

class Ui_w_chatwindow(object):
    def setupUi(self, w_chatwindow):
        w_chatwindow.setObjectName("w_chatwindow")
        w_chatwindow.resize(568, 721)
        self.centralwidget = QtGui.QWidget(w_chatwindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.splitter_2 = QtGui.QSplitter(self.centralwidget)
        self.splitter_2.setLineWidth(0)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setHandleWidth(12)
        self.splitter_2.setObjectName("splitter_2")
        self.w_chatframe = QtGui.QFrame(self.splitter_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.w_chatframe.sizePolicy().hasHeightForWidth())
        self.w_chatframe.setSizePolicy(sizePolicy)
        self.w_chatframe.setFrameShadow(QtGui.QFrame.Raised)
        self.w_chatframe.setLineWidth(0)
        self.w_chatframe.setObjectName("w_chatframe")
        self.gridLayout = QtGui.QGridLayout(self.w_chatframe)
        self.gridLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter = QtGui.QSplitter(self.w_chatframe)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setHandleWidth(12)
        self.splitter.setObjectName("splitter")
        self.userlist = QtGui.QListWidget(self.splitter)
        self.userlist.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.userlist.sizePolicy().hasHeightForWidth())
        self.userlist.setSizePolicy(sizePolicy)
        self.userlist.setStyleSheet("font: 8pt;")
        self.userlist.setObjectName("userlist")
        QtGui.QListWidgetItem(self.userlist)
        QtGui.QListWidgetItem(self.userlist)
        QtGui.QListWidgetItem(self.userlist)
        self.convtext = QtGui.QTextBrowser(self.splitter)
        self.convtext.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.convtext.sizePolicy().hasHeightForWidth())
        self.convtext.setSizePolicy(sizePolicy)
        self.convtext.setAcceptDrops(False)
        self.convtext.setFrameShape(QtGui.QFrame.StyledPanel)
        self.convtext.setFrameShadow(QtGui.QFrame.Sunken)
        self.convtext.setOpenLinks(False)
        self.convtext.setObjectName("convtext")
        self.gridLayout.addWidget(self.splitter, 0, 0, 1, 1)
        self.w_inputframe_2 = QtGui.QFrame(self.splitter_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.w_inputframe_2.sizePolicy().hasHeightForWidth())
        self.w_inputframe_2.setSizePolicy(sizePolicy)
        self.w_inputframe_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.w_inputframe_2.setFrameShadow(QtGui.QFrame.Plain)
        self.w_inputframe_2.setObjectName("w_inputframe_2")
        self.w_inputframe = QtGui.QVBoxLayout(self.w_inputframe_2)
        self.w_inputframe.setMargin(0)
        self.w_inputframe.setObjectName("w_inputframe")
        self.w_formatframe = QtGui.QFrame(self.w_inputframe_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w_formatframe.sizePolicy().hasHeightForWidth())
        self.w_formatframe.setSizePolicy(sizePolicy)
        self.w_formatframe.setAutoFillBackground(True)
        self.w_formatframe.setFrameShape(QtGui.QFrame.NoFrame)
        self.w_formatframe.setFrameShadow(QtGui.QFrame.Plain)
        self.w_formatframe.setObjectName("w_formatframe")
        self.gridLayout_3 = QtGui.QGridLayout(self.w_formatframe)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.font = QtGui.QFontComboBox(self.w_formatframe)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.font.sizePolicy().hasHeightForWidth())
        self.font.setSizePolicy(sizePolicy)
        self.font.setObjectName("font")
        self.gridLayout_3.addWidget(self.font, 0, 6, 1, 1)
        self.italic = QtGui.QToolButton(self.w_formatframe)
        self.italic.setEnabled(True)
        self.italic.setFocusPolicy(QtCore.Qt.NoFocus)
        self.italic.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/res/16x16/actions/format-text-italic.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.italic.setIcon(icon)
        self.italic.setCheckable(True)
        self.italic.setChecked(False)
        self.italic.setObjectName("italic")
        self.gridLayout_3.addWidget(self.italic, 0, 1, 1, 2)
        self.bold = QtGui.QToolButton(self.w_formatframe)
        self.bold.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bold.sizePolicy().hasHeightForWidth())
        self.bold.setSizePolicy(sizePolicy)
        self.bold.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bold.setText("None")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/res/16x16/actions/format-text-bold.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/actions/format-text-bold.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.bold.setIcon(icon1)
        self.bold.setIconSize(QtCore.QSize(24, 24))
        self.bold.setCheckable(True)
        self.bold.setChecked(False)
        self.bold.setObjectName("bold")
        self.gridLayout_3.addWidget(self.bold, 0, 0, 1, 1)
        self.fontsize = QtGui.QComboBox(self.w_formatframe)
        self.fontsize.setEditable(True)
        self.fontsize.setObjectName("fontsize")
        self.fontsize.addItem("")
        self.fontsize.addItem("")
        self.gridLayout_3.addWidget(self.fontsize, 0, 7, 1, 1)
        self.underline = QtGui.QToolButton(self.w_formatframe)
        self.underline.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.underline.sizePolicy().hasHeightForWidth())
        self.underline.setSizePolicy(sizePolicy)
        self.underline.setFocusPolicy(QtCore.Qt.NoFocus)
        self.underline.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/res/16x16/actions/format-text-underline.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.underline.setIcon(icon2)
        self.underline.setIconSize(QtCore.QSize(24, 24))
        self.underline.setCheckable(True)
        self.underline.setChecked(False)
        self.underline.setObjectName("underline")
        self.gridLayout_3.addWidget(self.underline, 0, 4, 1, 1)
        spacerItem = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 0, 8, 1, 1)
        self.fg_color = QtGui.QToolButton(self.w_formatframe)
        self.fg_color.setMinimumSize(QtCore.QSize(24, 32))
        self.fg_color.setText("")
        self.fg_color.setObjectName("fg_color")
        self.gridLayout_3.addWidget(self.fg_color, 0, 5, 1, 1)
        self.w_inputframe.addWidget(self.w_formatframe)
        self.input = QtGui.QTextEdit(self.w_inputframe_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input.sizePolicy().hasHeightForWidth())
        self.input.setSizePolicy(sizePolicy)
        self.input.setFrameShadow(QtGui.QFrame.Sunken)
        self.input.setAcceptRichText(True)
        self.input.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextEditable|QtCore.Qt.TextEditorInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.input.setObjectName("input")
        self.w_inputframe.addWidget(self.input)
        self.gridLayout_2.addWidget(self.splitter_2, 0, 0, 1, 1)
        w_chatwindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(w_chatwindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 568, 29))
        self.menubar.setObjectName("menubar")
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuActions = QtGui.QMenu(self.menubar)
        self.menuActions.setObjectName("menuActions")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        w_chatwindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(w_chatwindow)
        self.statusbar.setObjectName("statusbar")
        w_chatwindow.setStatusBar(self.statusbar)
        self.actionShow_Formatting_Toolbox = QtGui.QAction(w_chatwindow)
        self.actionShow_Formatting_Toolbox.setCheckable(True)
        self.actionShow_Formatting_Toolbox.setChecked(True)
        self.actionShow_Formatting_Toolbox.setObjectName("actionShow_Formatting_Toolbox")
        self.actionShow_User_List = QtGui.QAction(w_chatwindow)
        self.actionShow_User_List.setCheckable(True)
        self.actionShow_User_List.setChecked(True)
        self.actionShow_User_List.setObjectName("actionShow_User_List")
        self.actionShow_Backlog = QtGui.QAction(w_chatwindow)
        self.actionShow_Backlog.setObjectName("actionShow_Backlog")
        self.actionClose = QtGui.QAction(w_chatwindow)
        self.actionClose.setObjectName("actionClose")
        self.menuView.addAction(self.actionShow_Formatting_Toolbox)
        self.menuActions.addAction(self.actionShow_Backlog)
        self.menuFile.addAction(self.actionClose)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuActions.menuAction())
        self.menubar.addAction(self.menuView.menuAction())

        self.retranslateUi(w_chatwindow)
        QtCore.QObject.connect(self.font, QtCore.SIGNAL("currentFontChanged(QFont)"), self.input.setCurrentFont)
        QtCore.QObject.connect(self.actionShow_Formatting_Toolbox, QtCore.SIGNAL("toggled(bool)"), self.w_formatframe.setVisible)
        QtCore.QObject.connect(self.actionShow_User_List, QtCore.SIGNAL("toggled(bool)"), self.userlist.setVisible)
        QtCore.QObject.connect(self.italic, QtCore.SIGNAL("toggled(bool)"), self.input.setFontItalic)
        QtCore.QObject.connect(self.underline, QtCore.SIGNAL("toggled(bool)"), self.input.setFontUnderline)
        QtCore.QObject.connect(self.actionClose, QtCore.SIGNAL("activated()"), w_chatwindow.close)
        QtCore.QMetaObject.connectSlotsByName(w_chatwindow)

    def retranslateUi(self, w_chatwindow):
        w_chatwindow.setWindowTitle(QtGui.QApplication.translate("w_chatwindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.userlist.isSortingEnabled()
        self.userlist.setSortingEnabled(False)
        self.userlist.item(0).setText(QtGui.QApplication.translate("w_chatwindow", "foo", None, QtGui.QApplication.UnicodeUTF8))
        self.userlist.item(1).setText(QtGui.QApplication.translate("w_chatwindow", "bar", None, QtGui.QApplication.UnicodeUTF8))
        self.userlist.item(2).setText(QtGui.QApplication.translate("w_chatwindow", "baz", None, QtGui.QApplication.UnicodeUTF8))
        self.userlist.setSortingEnabled(__sortingEnabled)
        self.convtext.setHtml(QtGui.QApplication.translate("w_chatwindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Lucida Grande\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">hello world</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.italic.setShortcut(QtGui.QApplication.translate("w_chatwindow", "Ctrl+I", None, QtGui.QApplication.UnicodeUTF8))
        self.bold.setShortcut(QtGui.QApplication.translate("w_chatwindow", "Ctrl+B", None, QtGui.QApplication.UnicodeUTF8))
        self.fontsize.setItemText(0, QtGui.QApplication.translate("w_chatwindow", "10", None, QtGui.QApplication.UnicodeUTF8))
        self.fontsize.setItemText(1, QtGui.QApplication.translate("w_chatwindow", "12", None, QtGui.QApplication.UnicodeUTF8))
        self.underline.setShortcut(QtGui.QApplication.translate("w_chatwindow", "Ctrl+U", None, QtGui.QApplication.UnicodeUTF8))
        self.input.setHtml(QtGui.QApplication.translate("w_chatwindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Lucida Grande\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.menuView.setTitle(QtGui.QApplication.translate("w_chatwindow", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.menuActions.setTitle(QtGui.QApplication.translate("w_chatwindow", "Actions", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("w_chatwindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShow_Formatting_Toolbox.setText(QtGui.QApplication.translate("w_chatwindow", "Formatting Toolbox", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShow_Formatting_Toolbox.setShortcut(QtGui.QApplication.translate("w_chatwindow", "Ctrl+Shift+F", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShow_User_List.setText(QtGui.QApplication.translate("w_chatwindow", "User List", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShow_Backlog.setText(QtGui.QApplication.translate("w_chatwindow", "Show Backlog", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClose.setText(QtGui.QApplication.translate("w_chatwindow", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClose.setShortcut(QtGui.QApplication.translate("w_chatwindow", "Alt+W", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    w_chatwindow = QtGui.QMainWindow()
    ui = Ui_w_chatwindow()
    ui.setupUi(w_chatwindow)
    def _kp(event):
        if not event.key() == QtCore.Qt.Key_Return:
            QtGui.QTextEdit.keyPressEvent(ui.input, event)
            return
        print ui.input.toHtml()
        ui.input.clear()
        d = ui.input.document()
        d.setDefaultStyleSheet("")

    ui.input.keyPressEvent = _kp
    w_chatwindow.show()
    sys.exit(app.exec_())

