# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'connection_properties.ui'
#
# Created: Fri Sep 17 20:49:29 2010
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_connection_widget(object):
    def setupUi(self, connection_widget):
        connection_widget.setObjectName("connection_widget")
        connection_widget.resize(269, 352)
        self.gridLayout = QtGui.QGridLayout(connection_widget)
        self.gridLayout.setMargin(3)
        self.gridLayout.setObjectName("gridLayout")
        self._userlabel = QtGui.QLabel(connection_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._userlabel.sizePolicy().hasHeightForWidth())
        self._userlabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self._userlabel.setFont(font)
        self._userlabel.setObjectName("_userlabel")
        self.gridLayout.addWidget(self._userlabel, 0, 0, 1, 1)
        self.w_username = QtGui.QLineEdit(connection_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w_username.sizePolicy().hasHeightForWidth())
        self.w_username.setSizePolicy(sizePolicy)
        self.w_username.setText("")
        self.w_username.setObjectName("w_username")
        self.gridLayout.addWidget(self.w_username, 0, 1, 1, 2)
        self._passwordlabel = QtGui.QLabel(connection_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._passwordlabel.sizePolicy().hasHeightForWidth())
        self._passwordlabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self._passwordlabel.setFont(font)
        self._passwordlabel.setObjectName("_passwordlabel")
        self.gridLayout.addWidget(self._passwordlabel, 1, 0, 1, 1)
        self.w_password = QtGui.QLineEdit(connection_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w_password.sizePolicy().hasHeightForWidth())
        self.w_password.setSizePolicy(sizePolicy)
        self.w_password.setInputMask("")
        self.w_password.setText("")
        self.w_password.setEchoMode(QtGui.QLineEdit.Password)
        self.w_password.setObjectName("w_password")
        self.gridLayout.addWidget(self.w_password, 1, 1, 1, 2)
        self._protolabel = QtGui.QLabel(connection_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._protolabel.sizePolicy().hasHeightForWidth())
        self._protolabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self._protolabel.setFont(font)
        self._protolabel.setObjectName("_protolabel")
        self.gridLayout.addWidget(self._protolabel, 2, 0, 1, 1)
        self.w_improto = QtGui.QComboBox(connection_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w_improto.sizePolicy().hasHeightForWidth())
        self.w_improto.setSizePolicy(sizePolicy)
        self.w_improto.setObjectName("w_improto")
        self.gridLayout.addWidget(self.w_improto, 2, 1, 1, 2)
        self.show_proxy_prefs = QtGui.QToolButton(connection_widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.show_proxy_prefs.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/stock_proxy.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.show_proxy_prefs.setIcon(icon)
        self.show_proxy_prefs.setIconSize(QtCore.QSize(16, 16))
        self.show_proxy_prefs.setCheckable(True)
        self.show_proxy_prefs.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.show_proxy_prefs.setAutoRaise(True)
        self.show_proxy_prefs.setObjectName("show_proxy_prefs")
        self.gridLayout.addWidget(self.show_proxy_prefs, 4, 0, 1, 2)
        self.w_connect = QtGui.QPushButton(connection_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w_connect.sizePolicy().hasHeightForWidth())
        self.w_connect.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.w_connect.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/network-connect.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.w_connect.setIcon(icon1)
        self.w_connect.setObjectName("w_connect")
        self.gridLayout.addWidget(self.w_connect, 7, 2, 1, 1)
        self.conn_close = QtGui.QPushButton(connection_widget)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.conn_close.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/dialog-close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.conn_close.setIcon(icon2)
        self.conn_close.setObjectName("conn_close")
        self.gridLayout.addWidget(self.conn_close, 7, 1, 1, 1)
        self.proxy_params = QtGui.QFrame(connection_widget)
        self.proxy_params.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.proxy_params.sizePolicy().hasHeightForWidth())
        self.proxy_params.setSizePolicy(sizePolicy)
        self.proxy_params.setFrameShape(QtGui.QFrame.NoFrame)
        self.proxy_params.setFrameShadow(QtGui.QFrame.Raised)
        self.proxy_params.setLineWidth(1)
        self.proxy_params.setObjectName("proxy_params")
        self.gridLayout_4 = QtGui.QGridLayout(self.proxy_params)
        self.gridLayout_4.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.gridLayout_4.setMargin(5)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.proxy_type_socks4 = QtGui.QRadioButton(self.proxy_params)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.proxy_type_socks4.setFont(font)
        self.proxy_type_socks4.setObjectName("proxy_type_socks4")
        self.gridLayout_4.addWidget(self.proxy_type_socks4, 1, 0, 1, 1)
        self.proxy_type_http = QtGui.QRadioButton(self.proxy_params)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.proxy_type_http.setFont(font)
        self.proxy_type_http.setChecked(True)
        self.proxy_type_http.setObjectName("proxy_type_http")
        self.gridLayout_4.addWidget(self.proxy_type_http, 1, 3, 1, 1)
        self.proxy_port = QtGui.QLineEdit(self.proxy_params)
        self.proxy_port.setObjectName("proxy_port")
        self.gridLayout_4.addWidget(self.proxy_port, 4, 2, 1, 3)
        self.proxy_password = QtGui.QLineEdit(self.proxy_params)
        self.proxy_password.setEchoMode(QtGui.QLineEdit.Password)
        self.proxy_password.setObjectName("proxy_password")
        self.gridLayout_4.addWidget(self.proxy_password, 8, 2, 1, 3)
        self.label_2 = QtGui.QLabel(self.proxy_params)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 8, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.proxy_params)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 4, 0, 1, 1)
        self.proxy_host = QtGui.QLineEdit(self.proxy_params)
        self.proxy_host.setObjectName("proxy_host")
        self.gridLayout_4.addWidget(self.proxy_host, 3, 2, 1, 3)
        self.label = QtGui.QLabel(self.proxy_params)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 7, 0, 1, 1)
        self.proxy_type_socks5 = QtGui.QRadioButton(self.proxy_params)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.proxy_type_socks5.setFont(font)
        self.proxy_type_socks5.setChecked(False)
        self.proxy_type_socks5.setObjectName("proxy_type_socks5")
        self.gridLayout_4.addWidget(self.proxy_type_socks5, 1, 2, 1, 1)
        self.label_4 = QtGui.QLabel(self.proxy_params)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 3, 0, 1, 1)
        self.proxy_username = QtGui.QLineEdit(self.proxy_params)
        self.proxy_username.setObjectName("proxy_username")
        self.gridLayout_4.addWidget(self.proxy_username, 7, 2, 1, 3)
        self.gridLayout.addWidget(self.proxy_params, 6, 0, 1, 3)
        self.line = QtGui.QFrame(connection_widget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 3, 0, 1, 3)
        spacerItem = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 5, 0, 1, 1)
        self._userlabel.setBuddy(self.w_username)
        self._passwordlabel.setBuddy(self.w_password)
        self._protolabel.setBuddy(self.w_improto)
        self.label_2.setBuddy(self.proxy_password)
        self.label_3.setBuddy(self.proxy_port)
        self.label.setBuddy(self.proxy_username)
        self.label_4.setBuddy(self.proxy_host)

        self.retranslateUi(connection_widget)
        QtCore.QObject.connect(self.conn_close, QtCore.SIGNAL("clicked()"), connection_widget.hide)
        QtCore.QMetaObject.connectSlotsByName(connection_widget)
        connection_widget.setTabOrder(self.w_username, self.w_password)
        connection_widget.setTabOrder(self.w_password, self.w_improto)
        connection_widget.setTabOrder(self.w_improto, self.show_proxy_prefs)
        connection_widget.setTabOrder(self.show_proxy_prefs, self.proxy_type_socks4)
        connection_widget.setTabOrder(self.proxy_type_socks4, self.proxy_type_socks5)
        connection_widget.setTabOrder(self.proxy_type_socks5, self.proxy_type_http)
        connection_widget.setTabOrder(self.proxy_type_http, self.proxy_host)
        connection_widget.setTabOrder(self.proxy_host, self.proxy_port)
        connection_widget.setTabOrder(self.proxy_port, self.proxy_username)
        connection_widget.setTabOrder(self.proxy_username, self.proxy_password)

    def retranslateUi(self, connection_widget):
        connection_widget.setWindowTitle(QtGui.QApplication.translate("connection_widget", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self._userlabel.setText(QtGui.QApplication.translate("connection_widget", "Username", None, QtGui.QApplication.UnicodeUTF8))
        self._passwordlabel.setText(QtGui.QApplication.translate("connection_widget", "Password", None, QtGui.QApplication.UnicodeUTF8))
        self._protolabel.setText(QtGui.QApplication.translate("connection_widget", "Protocol", None, QtGui.QApplication.UnicodeUTF8))
        self.show_proxy_prefs.setText(QtGui.QApplication.translate("connection_widget", "Use Proxy ...", None, QtGui.QApplication.UnicodeUTF8))
        self.w_connect.setText(QtGui.QApplication.translate("connection_widget", "Connect", None, QtGui.QApplication.UnicodeUTF8))
        self.conn_close.setText(QtGui.QApplication.translate("connection_widget", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.proxy_type_socks4.setText(QtGui.QApplication.translate("connection_widget", "SOCKS4", None, QtGui.QApplication.UnicodeUTF8))
        self.proxy_type_http.setText(QtGui.QApplication.translate("connection_widget", "HTTP", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("connection_widget", "Password", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("connection_widget", "Port", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("connection_widget", "Username", None, QtGui.QApplication.UnicodeUTF8))
        self.proxy_type_socks5.setText(QtGui.QApplication.translate("connection_widget", "SOCKS5", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("connection_widget", "Address", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    connection_widget = QtGui.QWidget()
    ui = Ui_connection_widget()
    ui.setupUi(connection_widget)
    connection_widget.show()
    sys.exit(app.exec_())

