# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'triviaopts.ui'
#
# Created: Tue Oct  5 20:12:45 2010
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_trivia_mw(object):
    def setupUi(self, trivia_mw):
        trivia_mw.setObjectName("trivia_mw")
        trivia_mw.resize(329, 871)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(trivia_mw.sizePolicy().hasHeightForWidth())
        trivia_mw.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/yobot_icons/icons/custom/yobot_24_h.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        trivia_mw.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(trivia_mw)
        self.centralwidget.setObjectName("centralwidget")
        self.mainLayout = QtGui.QGridLayout(self.centralwidget)
        self.mainLayout.setObjectName("mainLayout")
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label_17 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        self.label_17.setObjectName("label_17")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_17)
        self.account = QtGui.QComboBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.account.sizePolicy().hasHeightForWidth())
        self.account.setSizePolicy(sizePolicy)
        self.account.setObjectName("account")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.account)
        self.label_18 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        self.label_18.setObjectName("label_18")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_18)
        self.room = QtGui.QComboBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.room.sizePolicy().hasHeightForWidth())
        self.room.setSizePolicy(sizePolicy)
        self.room.setEditable(True)
        self.room.setObjectName("room")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.room)
        self.mainLayout.addLayout(self.formLayout, 0, 0, 1, 2)
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.mainLayout.addWidget(self.line_2, 1, 0, 1, 2)
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_15 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setObjectName("label_15")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_15)
        self.questions_type = QtGui.QComboBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.questions_type.sizePolicy().hasHeightForWidth())
        self.questions_type.setSizePolicy(sizePolicy)
        self.questions_type.setObjectName("questions_type")
        self.questions_type.addItem("")
        self.questions_type.addItem("")
        self.questions_type.addItem("")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.questions_type)
        self.label_12 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setObjectName("label_12")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_12)
        self.post_interval = QtGui.QSpinBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.post_interval.sizePolicy().hasHeightForWidth())
        self.post_interval.setSizePolicy(sizePolicy)
        self.post_interval.setProperty("value", 15)
        self.post_interval.setObjectName("post_interval")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.post_interval)
        self.label_16 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setObjectName("label_16")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_16)
        self.answer_timeout = QtGui.QSpinBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.answer_timeout.sizePolicy().hasHeightForWidth())
        self.answer_timeout.setSizePolicy(sizePolicy)
        self.answer_timeout.setProperty("value", 30)
        self.answer_timeout.setObjectName("answer_timeout")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.answer_timeout)
        self.mainLayout.addLayout(self.formLayout_2, 2, 0, 1, 1)
        self.formLayout_3 = QtGui.QFormLayout()
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_11 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setObjectName("label_11")
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_11)
        self.amount = QtGui.QSpinBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.amount.sizePolicy().hasHeightForWidth())
        self.amount.setSizePolicy(sizePolicy)
        self.amount.setProperty("value", 35)
        self.amount.setObjectName("amount")
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.amount)
        self.label_13 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setObjectName("label_13")
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_13)
        self.percent_anagrams = QtGui.QSpinBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.percent_anagrams.sizePolicy().hasHeightForWidth())
        self.percent_anagrams.setSizePolicy(sizePolicy)
        self.percent_anagrams.setMaximum(100)
        self.percent_anagrams.setProperty("value", 50)
        self.percent_anagrams.setObjectName("percent_anagrams")
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.percent_anagrams)
        self.label_14 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setObjectName("label_14")
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_14)
        self.percent_trivia = QtGui.QSpinBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.percent_trivia.sizePolicy().hasHeightForWidth())
        self.percent_trivia.setSizePolicy(sizePolicy)
        self.percent_trivia.setMaximum(100)
        self.percent_trivia.setProperty("value", 50)
        self.percent_trivia.setObjectName("percent_trivia")
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.FieldRole, self.percent_trivia)
        self.mainLayout.addLayout(self.formLayout_3, 2, 1, 1, 1)
        self.line_5 = QtGui.QFrame(self.centralwidget)
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.mainLayout.addWidget(self.line_5, 3, 0, 1, 2)
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.mainLayout.addWidget(self.line, 7, 0, 1, 2)
        self.updatedb_bool = QtGui.QCheckBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.updatedb_bool.sizePolicy().hasHeightForWidth())
        self.updatedb_bool.setSizePolicy(sizePolicy)
        self.updatedb_bool.setObjectName("updatedb_bool")
        self.mainLayout.addWidget(self.updatedb_bool, 9, 0, 1, 1)
        self.change_font = QtGui.QPushButton(self.centralwidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/format-text-color.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.change_font.setIcon(icon1)
        self.change_font.setObjectName("change_font")
        self.mainLayout.addWidget(self.change_font, 9, 1, 1, 1)
        self.line_3 = QtGui.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.mainLayout.addWidget(self.line_3, 12, 0, 1, 2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.start = QtGui.QToolButton(self.centralwidget)
        self.start.setMinimumSize(QtCore.QSize(30, 0))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/res/16x16/actions/media-playback-start.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.start.setIcon(icon2)
        self.start.setObjectName("start")
        self.horizontalLayout.addWidget(self.start)
        self.pause = QtGui.QToolButton(self.centralwidget)
        self.pause.setMinimumSize(QtCore.QSize(30, 0))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/res/16x16/actions/media-playback-pause.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pause.setIcon(icon3)
        self.pause.setObjectName("pause")
        self.horizontalLayout.addWidget(self.pause)
        self.stop = QtGui.QToolButton(self.centralwidget)
        self.stop.setMinimumSize(QtCore.QSize(30, 0))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/res/16x16/actions/media-playback-stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stop.setIcon(icon4)
        self.stop.setObjectName("stop")
        self.horizontalLayout.addWidget(self.stop)
        self.next = QtGui.QToolButton(self.centralwidget)
        self.next.setMinimumSize(QtCore.QSize(30, 0))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/res/16x16/actions/media-skip-forward.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.next.setIcon(icon5)
        self.next.setObjectName("next")
        self.horizontalLayout.addWidget(self.next)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.mainLayout.addLayout(self.horizontalLayout, 14, 0, 1, 2)
        self.anagrams_opts = QtGui.QGroupBox(self.centralwidget)
        self.anagrams_opts.setObjectName("anagrams_opts")
        self.gridLayout_4 = QtGui.QGridLayout(self.anagrams_opts)
        self.gridLayout_4.setContentsMargins(-1, -1, 5, 5)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setHorizontalSpacing(6)
        self.gridLayout_3.setVerticalSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.anagrams_database = QtGui.QLineEdit(self.anagrams_opts)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.anagrams_database.sizePolicy().hasHeightForWidth())
        self.anagrams_database.setSizePolicy(sizePolicy)
        self.anagrams_database.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.anagrams_database.setReadOnly(True)
        self.anagrams_database.setObjectName("anagrams_database")
        self.gridLayout_3.addWidget(self.anagrams_database, 6, 2, 1, 1)
        self.select_anagrams_dbfile = QtGui.QPushButton(self.anagrams_opts)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.select_anagrams_dbfile.sizePolicy().hasHeightForWidth())
        self.select_anagrams_dbfile.setSizePolicy(sizePolicy)
        self.select_anagrams_dbfile.setMaximumSize(QtCore.QSize(45, 27))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/res/16x16/places/server-database.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.select_anagrams_dbfile.setIcon(icon6)
        self.select_anagrams_dbfile.setObjectName("select_anagrams_dbfile")
        self.gridLayout_3.addWidget(self.select_anagrams_dbfile, 6, 3, 1, 1)
        self.label_5 = QtGui.QLabel(self.anagrams_opts)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setScaledContents(False)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 6, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 0, 1, 2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtGui.QLabel(self.anagrams_opts)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.anagrams_letters_min = QtGui.QSpinBox(self.anagrams_opts)
        self.anagrams_letters_min.setSuffix("")
        self.anagrams_letters_min.setPrefix("")
        self.anagrams_letters_min.setObjectName("anagrams_letters_min")
        self.horizontalLayout_3.addWidget(self.anagrams_letters_min)
        self.label_3 = QtGui.QLabel(self.anagrams_opts)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.anagrams_letters_max = QtGui.QSpinBox(self.anagrams_opts)
        self.anagrams_letters_max.setSuffix("")
        self.anagrams_letters_max.setPrefix("")
        self.anagrams_letters_max.setObjectName("anagrams_letters_max")
        self.horizontalLayout_3.addWidget(self.anagrams_letters_max)
        self.label_4 = QtGui.QLabel(self.anagrams_opts)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.gridLayout_4.addLayout(self.horizontalLayout_3, 1, 0, 1, 2)
        self.anagrams_caps_hint = QtGui.QCheckBox(self.anagrams_opts)
        self.anagrams_caps_hint.setObjectName("anagrams_caps_hint")
        self.gridLayout_4.addWidget(self.anagrams_caps_hint, 2, 0, 1, 1)
        self.anagrams_use_nfixes = QtGui.QCheckBox(self.anagrams_opts)
        self.anagrams_use_nfixes.setObjectName("anagrams_use_nfixes")
        self.gridLayout_4.addWidget(self.anagrams_use_nfixes, 3, 0, 1, 1)
        self.suffix_prefix_options = QtGui.QFrame(self.anagrams_opts)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.suffix_prefix_options.sizePolicy().hasHeightForWidth())
        self.suffix_prefix_options.setSizePolicy(sizePolicy)
        self.suffix_prefix_options.setObjectName("suffix_prefix_options")
        self.suffix_prefix_opts = QtGui.QGridLayout(self.suffix_prefix_options)
        self.suffix_prefix_opts.setContentsMargins(0, 10, 0, 0)
        self.suffix_prefix_opts.setObjectName("suffix_prefix_opts")
        self.label_6 = QtGui.QLabel(self.suffix_prefix_options)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setBold(True)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.suffix_prefix_opts.addWidget(self.label_6, 1, 0, 1, 1)
        self.prefix_list = QtGui.QListWidget(self.suffix_prefix_options)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prefix_list.sizePolicy().hasHeightForWidth())
        self.prefix_list.setSizePolicy(sizePolicy)
        self.prefix_list.setMaximumSize(QtCore.QSize(16777215, 125))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.prefix_list.setFont(font)
        self.prefix_list.setObjectName("prefix_list")
        self.suffix_prefix_opts.addWidget(self.prefix_list, 3, 0, 1, 1)
        self.suffix_list = QtGui.QListWidget(self.suffix_prefix_options)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.suffix_list.sizePolicy().hasHeightForWidth())
        self.suffix_list.setSizePolicy(sizePolicy)
        self.suffix_list.setMaximumSize(QtCore.QSize(16777215, 125))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.suffix_list.setFont(font)
        self.suffix_list.setObjectName("suffix_list")
        self.suffix_prefix_opts.addWidget(self.suffix_list, 3, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.suffix_prefix_options)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setBold(True)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.suffix_prefix_opts.addWidget(self.label_7, 1, 1, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setContentsMargins(0, 0, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.prefix_input = QtGui.QLineEdit(self.suffix_prefix_options)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.prefix_input.setFont(font)
        self.prefix_input.setObjectName("prefix_input")
        self.horizontalLayout_2.addWidget(self.prefix_input)
        self.prefix_add = QtGui.QToolButton(self.suffix_prefix_options)
        self.prefix_add.setObjectName("prefix_add")
        self.horizontalLayout_2.addWidget(self.prefix_add)
        self.prefix_del = QtGui.QToolButton(self.suffix_prefix_options)
        self.prefix_del.setObjectName("prefix_del")
        self.horizontalLayout_2.addWidget(self.prefix_del)
        self.suffix_prefix_opts.addLayout(self.horizontalLayout_2, 4, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.suffix_input = QtGui.QLineEdit(self.suffix_prefix_options)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.suffix_input.setFont(font)
        self.suffix_input.setObjectName("suffix_input")
        self.horizontalLayout_4.addWidget(self.suffix_input)
        self.suffix_add = QtGui.QToolButton(self.suffix_prefix_options)
        self.suffix_add.setObjectName("suffix_add")
        self.horizontalLayout_4.addWidget(self.suffix_add)
        self.suffix_del = QtGui.QToolButton(self.suffix_prefix_options)
        self.suffix_del.setObjectName("suffix_del")
        self.horizontalLayout_4.addWidget(self.suffix_del)
        self.suffix_prefix_opts.addLayout(self.horizontalLayout_4, 4, 1, 1, 1)
        self.gridLayout_4.addWidget(self.suffix_prefix_options, 4, 0, 1, 2)
        self.mainLayout.addWidget(self.anagrams_opts, 5, 0, 1, 2)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.mainLayout.addItem(spacerItem2, 13, 0, 1, 1)
        self.questions_opts = QtGui.QGroupBox(self.centralwidget)
        self.questions_opts.setObjectName("questions_opts")
        self.gridLayout_2 = QtGui.QGridLayout(self.questions_opts)
        self.gridLayout_2.setContentsMargins(-1, -1, 5, 5)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setHorizontalSpacing(6)
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.questions_database = QtGui.QLineEdit(self.questions_opts)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.questions_database.sizePolicy().hasHeightForWidth())
        self.questions_database.setSizePolicy(sizePolicy)
        self.questions_database.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.questions_database.setReadOnly(True)
        self.questions_database.setObjectName("questions_database")
        self.gridLayout.addWidget(self.questions_database, 6, 2, 1, 1)
        self.select_questions_dbfile = QtGui.QPushButton(self.questions_opts)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.select_questions_dbfile.sizePolicy().hasHeightForWidth())
        self.select_questions_dbfile.setSizePolicy(sizePolicy)
        self.select_questions_dbfile.setMaximumSize(QtCore.QSize(45, 27))
        self.select_questions_dbfile.setIcon(icon6)
        self.select_questions_dbfile.setObjectName("select_questions_dbfile")
        self.gridLayout.addWidget(self.select_questions_dbfile, 6, 3, 1, 1)
        self.label = QtGui.QLabel(self.questions_opts)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setScaledContents(False)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 6, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 3)
        self.questions_categories_params = QtGui.QFrame(self.questions_opts)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.questions_categories_params.sizePolicy().hasHeightForWidth())
        self.questions_categories_params.setSizePolicy(sizePolicy)
        self.questions_categories_params.setMaximumSize(QtCore.QSize(16777215, 150))
        self.questions_categories_params.setFrameShape(QtGui.QFrame.NoFrame)
        self.questions_categories_params.setFrameShadow(QtGui.QFrame.Raised)
        self.questions_categories_params.setObjectName("questions_categories_params")
        self.gridLayout_5 = QtGui.QGridLayout(self.questions_categories_params)
        self.gridLayout_5.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.gridLayout_5.setMargin(0)
        self.gridLayout_5.setVerticalSpacing(3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.questions_categories = QtGui.QListWidget(self.questions_categories_params)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.questions_categories.sizePolicy().hasHeightForWidth())
        self.questions_categories.setSizePolicy(sizePolicy)
        self.questions_categories.setMaximumSize(QtCore.QSize(16777215, 125))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.questions_categories.setFont(font)
        self.questions_categories.setObjectName("questions_categories")
        self.gridLayout_5.addWidget(self.questions_categories, 2, 0, 1, 1)
        self.selected_categories = QtGui.QListWidget(self.questions_categories_params)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selected_categories.sizePolicy().hasHeightForWidth())
        self.selected_categories.setSizePolicy(sizePolicy)
        self.selected_categories.setMaximumSize(QtCore.QSize(16777215, 125))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.selected_categories.setFont(font)
        self.selected_categories.setObjectName("selected_categories")
        self.gridLayout_5.addWidget(self.selected_categories, 2, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.questions_categories_params)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setBold(True)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout_5.addWidget(self.label_8, 1, 0, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(-1, -1, -1, 4)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.questions_blacklist = QtGui.QRadioButton(self.questions_categories_params)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.questions_blacklist.setFont(font)
        self.questions_blacklist.setChecked(True)
        self.questions_blacklist.setObjectName("questions_blacklist")
        self.horizontalLayout_5.addWidget(self.questions_blacklist)
        self.questions_whitelist = QtGui.QRadioButton(self.questions_categories_params)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.questions_whitelist.setFont(font)
        self.questions_whitelist.setObjectName("questions_whitelist")
        self.horizontalLayout_5.addWidget(self.questions_whitelist)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.gridLayout_5.addLayout(self.horizontalLayout_5, 0, 0, 1, 2)
        self.label_9 = QtGui.QLabel(self.questions_categories_params)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setBold(True)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout_5.addWidget(self.label_9, 1, 1, 1, 1)
        self.gridLayout_2.addWidget(self.questions_categories_params, 4, 0, 1, 3)
        self.questions_use_categories = QtGui.QCheckBox(self.questions_opts)
        self.questions_use_categories.setObjectName("questions_use_categories")
        self.gridLayout_2.addWidget(self.questions_use_categories, 3, 0, 1, 1)
        self.mainLayout.addWidget(self.questions_opts, 4, 0, 1, 2)
        trivia_mw.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(trivia_mw)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 329, 29))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuProfile = QtGui.QMenu(self.menubar)
        self.menuProfile.setObjectName("menuProfile")
        self.menuComponents = QtGui.QMenu(self.menubar)
        self.menuComponents.setObjectName("menuComponents")
        trivia_mw.setMenuBar(self.menubar)
        self.actionConnect = QtGui.QAction(trivia_mw)
        self.actionConnect.setCheckable(True)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/icons/network-connect.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionConnect.setIcon(icon7)
        self.actionConnect.setObjectName("actionConnect")
        self.actionLoad = QtGui.QAction(trivia_mw)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/res/16x16/actions/document-open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLoad.setIcon(icon8)
        self.actionLoad.setObjectName("actionLoad")
        self.actionSave = QtGui.QAction(trivia_mw)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/res/16x16/actions/document-save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon9)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_As = QtGui.QAction(trivia_mw)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icons/res/16x16/actions/document-save-as.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave_As.setIcon(icon10)
        self.actionSave_As.setObjectName("actionSave_As")
        self.menuFile.addAction(self.actionConnect)
        self.menuProfile.addAction(self.actionLoad)
        self.menuProfile.addAction(self.actionSave)
        self.menuProfile.addAction(self.actionSave_As)
        self.menubar.addAction(self.menuProfile.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuComponents.menuAction())

        self.retranslateUi(trivia_mw)
        QtCore.QMetaObject.connectSlotsByName(trivia_mw)

    def retranslateUi(self, trivia_mw):
        trivia_mw.setWindowTitle(QtGui.QApplication.translate("trivia_mw", "Yobot Trivia", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("trivia_mw", "Account", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("trivia_mw", "Room", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("trivia_mw", "Type:", None, QtGui.QApplication.UnicodeUTF8))
        self.questions_type.setItemText(0, QtGui.QApplication.translate("trivia_mw", "Trivia", None, QtGui.QApplication.UnicodeUTF8))
        self.questions_type.setItemText(1, QtGui.QApplication.translate("trivia_mw", "Anagrams", None, QtGui.QApplication.UnicodeUTF8))
        self.questions_type.setItemText(2, QtGui.QApplication.translate("trivia_mw", "Mix", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("trivia_mw", "Interval", None, QtGui.QApplication.UnicodeUTF8))
        self.post_interval.setSuffix(QtGui.QApplication.translate("trivia_mw", " sec", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("trivia_mw", "Timeout", None, QtGui.QApplication.UnicodeUTF8))
        self.answer_timeout.setSuffix(QtGui.QApplication.translate("trivia_mw", " sec", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("trivia_mw", "Amount:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("trivia_mw", "Anagrams", None, QtGui.QApplication.UnicodeUTF8))
        self.percent_anagrams.setSuffix(QtGui.QApplication.translate("trivia_mw", "%", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("trivia_mw", "Trivia", None, QtGui.QApplication.UnicodeUTF8))
        self.percent_trivia.setSuffix(QtGui.QApplication.translate("trivia_mw", "%", None, QtGui.QApplication.UnicodeUTF8))
        self.updatedb_bool.setText(QtGui.QApplication.translate("trivia_mw", "Register Usage", None, QtGui.QApplication.UnicodeUTF8))
        self.change_font.setText(QtGui.QApplication.translate("trivia_mw", "Font", None, QtGui.QApplication.UnicodeUTF8))
        self.start.setText(QtGui.QApplication.translate("trivia_mw", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.pause.setText(QtGui.QApplication.translate("trivia_mw", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.stop.setText(QtGui.QApplication.translate("trivia_mw", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.next.setText(QtGui.QApplication.translate("trivia_mw", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.anagrams_opts.setTitle(QtGui.QApplication.translate("trivia_mw", "Anagram Options (Lengths, patterns)", None, QtGui.QApplication.UnicodeUTF8))
        self.select_anagrams_dbfile.setText(QtGui.QApplication.translate("trivia_mw", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("trivia_mw", "Database", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("trivia_mw", "From", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("trivia_mw", "to", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("trivia_mw", "letters", None, QtGui.QApplication.UnicodeUTF8))
        self.anagrams_caps_hint.setText(QtGui.QApplication.translate("trivia_mw", "Capitalize First Letter", None, QtGui.QApplication.UnicodeUTF8))
        self.anagrams_use_nfixes.setText(QtGui.QApplication.translate("trivia_mw", "Use prefixes and suffixes...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("trivia_mw", "Prefixes", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("trivia_mw", "Suffixes", None, QtGui.QApplication.UnicodeUTF8))
        self.prefix_add.setText(QtGui.QApplication.translate("trivia_mw", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.prefix_del.setText(QtGui.QApplication.translate("trivia_mw", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.suffix_add.setText(QtGui.QApplication.translate("trivia_mw", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.suffix_del.setText(QtGui.QApplication.translate("trivia_mw", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.questions_opts.setTitle(QtGui.QApplication.translate("trivia_mw", "Trivia Options (Categories)", None, QtGui.QApplication.UnicodeUTF8))
        self.select_questions_dbfile.setText(QtGui.QApplication.translate("trivia_mw", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("trivia_mw", "Database", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("trivia_mw", "Available Categories", None, QtGui.QApplication.UnicodeUTF8))
        self.questions_blacklist.setText(QtGui.QApplication.translate("trivia_mw", "Blacklist", None, QtGui.QApplication.UnicodeUTF8))
        self.questions_whitelist.setText(QtGui.QApplication.translate("trivia_mw", "Whitelist", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("trivia_mw", "Selected", None, QtGui.QApplication.UnicodeUTF8))
        self.questions_use_categories.setText(QtGui.QApplication.translate("trivia_mw", "Categories..", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("trivia_mw", "Actions", None, QtGui.QApplication.UnicodeUTF8))
        self.menuProfile.setTitle(QtGui.QApplication.translate("trivia_mw", "Profile", None, QtGui.QApplication.UnicodeUTF8))
        self.menuComponents.setTitle(QtGui.QApplication.translate("trivia_mw", "Components", None, QtGui.QApplication.UnicodeUTF8))
        self.actionConnect.setText(QtGui.QApplication.translate("trivia_mw", "Connect...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad.setText(QtGui.QApplication.translate("trivia_mw", "Load", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("trivia_mw", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_As.setText(QtGui.QApplication.translate("trivia_mw", "Save As", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc
import resources_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    trivia_mw = QtGui.QMainWindow()
    ui = Ui_trivia_mw()
    ui.setupUi(trivia_mw)
    trivia_mw.show()
    sys.exit(app.exec_())

